name: Deploy Laravel ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Deploy ke VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/laravel-action || exit 1
            if [ -f ".git/index.lock" ]; then
                sudo rm -f .git/index.lock
            fi
            sudo chown -R the-enc:www-data .git
            sudo chmod -R 775 .git
            git reset --hard
            git clean -fd
            git pull origin main || { echo "Gagal pull dari GitHub"; exit 1; }
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            composer install || { echo "Composer install gagal"; exit 1; }
            php artisan migrate || { echo "Migrasi database gagal"; exit 1; }
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart nginx || { echo "Restart Nginx gagal"; exit 1; }
