name: Deploy Laravel ke VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Deploy ke VPS
        uses: appleboy/ssh-action@master
        with:
          host: 103.127.99.247
          username: the-enc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo chown -R www-data:www-data /var/www/laravel-action
            sudo chmod -R 775 /var/www/laravel-action
            cd /var/www/laravel-action || exit 1
            if [ -f ".git/index.lock" ]; then
                sudo rm -f .git/index.lock
            fi
            sudo chown -R $(whoami):$(whoami) .git
            sudo chmod -R 775 .git
            git reset --hard
            git clean -fd
            git pull origin main || { echo "Gagal pull dari GitHub"; exit 1; }
            composer install --no-dev --optimize-autoloader || { echo "Composer install gagal"; exit 1; }
            php artisan migrate --force || { echo "Migrasi database gagal"; exit 1; }
            sudo systemctl restart nginx || { echo "Restart Nginx gagal"; exit 1; }
            echo "Deploy berhasil!"


